### ISSUE TITLE
IPv6 does not work

### ISSUE THREAD

**Issue by linozen** [konstruktoid/ansible-docker-rootless#17]
Hi there,

we tried getting rootlesskit (with slirp4netns) by following the documentation over here: https://wiki.archlinux.org/title/docker#IPv6 to enable outgoing traffic to IPv6-only hosts and even added the corresponding flag to the rootlesskit command in the systemd unit. Is there a way to enable rootless containers to connect to IPv6 hosts? And if so, might it make sense to include its configuration here as a variable? Would love to collaborate on this but at the moment I'm out of ideas.

Many thanks for considering!

**Comment by konstruktoid** [comment]
Hi @linozen 
I haven't tried getting IPv6 to work with Docker in a while, but can give it a try again.

If I/you/we find a way to enable it, it sure would be added as a configuration variable.

**Comment by mxmehl** [comment]
IPv6 in rootless would be great! I found a [parameter in rootlesskit](https://github.com/rootless-containers/rootlesskit/blob/50e88d6e889c88501455579a0177b42822bc26f2/docs/network.md#--netslirp4netns-recommended) via slirp4netns, but then docker becomes unresponsive. But I still struggle with understanding the interplay of the different components and debugging them properly, so @konstruktoid might be much more efficient here ;)

**Comment by konstruktoid** [comment]
So do I, @mxmehl , so do I. Even "before" rootless Docker networking was kind of messy.

I'll have a look at this, but I can't promise anything :)

**Comment by konstruktoid** [comment]
Sorry for the delay, I haven't been able to spend that much time on this issue as I would like and the time I've spent haven't really gotten med closer to anywhere.
