### ISSUE TITLE
galaxy is out of date

### ISSUE THREAD

**Issue by briceburg** [konstruktoid/ansible-docker-rootless#18]
Hi! Thanks for this awesome role. I'd like to begin consuming it, although I'm not sure that what is in galaxy is up to date with the current main branch that has more recent docker version (e.g. v0.1.0 in galaxy from 9mo ago does not contain https://github.com/konstruktoid/ansible-docker-rootless/commit/2ddeb3f59260606640f16b53309e866af6896cc8).

What is the recommended way to consume this role? Should we be pulling directly from a git ref?

**Comment by konstruktoid** [comment]
Hi and thanks for reporting this @briceburg 
I've simply forgotten to update the galaxy release. Will fix as soon as possible.

**Comment by konstruktoid** [comment]
https://galaxy.ansible.com/konstruktoid/docker_rootless v0.2.0 is now available.
