### ISSUE TITLE
docker_user = ansible_user

### ISSUE THREAD

**Issue by Dzeri96** [konstruktoid/ansible-docker-rootless#24]
So I want to install rootless docker for the user I'm installing most other services for in my playbook. Apart from the alias not being created for some reason, I don't want to have to use `sudo` in order to connect to the daemon my user is running. As far as I can see, that's the only option in the template, but for my case, setting the `DOCKER_HOST` env variable would suffice. 

Is this something we can implement? I think it would be straightforward and it has a very common use case in my opinion.

**Comment by konstruktoid** [comment]
Hi @Dzeri96, isn't setting `docker_user: "{{ ansible_user }}"` enough?
are you installing using the rootless packages or with a docker daemon on the server?

**Comment by konstruktoid** [comment]
`when: docker_add_alias|bool and not docker_rootful and docker_user != ansible_user` (https://github.com/konstruktoid/ansible-docker-rootless/blob/main/tasks/main.yml#L71) or something like that and a task settings only DOCKER_HOST if `docker_user = ansible_user` would probably fix that.

want to submit a PR?

**Comment by Dzeri96** [comment]
Sure, give me some time though as I'm currently involved in my master's thesis 😅
