### ISSUE TITLE
.bash_aliases and .bashrc are created in wrong user's directory

### ISSUE THREAD

**Issue by slhck** [konstruktoid/ansible-docker-rootless#35]
I ran this role against a server where the `docker_user` differed from the `ansible_user`, all using default options.

The tasks included these:

![image](https://user-images.githubusercontent.com/582444/161725930-341dbcd4-f77e-4aee-b12b-c23e263971f7.png)

It seems it modified the `.bash_aliases` of the `ansible_user`, and not the `docker_user`.

The error seems to be here: 

https://github.com/konstruktoid/ansible-docker-rootless/blob/88fd38143bdc436355d914525caff1e5db95b3f4/tasks/main.yml#L49

Should this be the `docker_user`? (Also affects surrounding tasks.)

**Comment by slhck** [comment]
Or maybe this was intentional and I didn't understand the purpose of these aliases. Sorry for the false alert in this case!

**Comment by konstruktoid** [comment]
No, that's expected, https://github.com/konstruktoid/ansible-docker-rootless/blob/main/tasks/main.yml#L37-L40 will add an alias so that `ansible_user` can run the `docker` command without needing to configure any variables.

**Comment by slhck** [comment]
Oh okay, got it.  I tried to improve the README to clarify that aspect.

**Comment by konstruktoid** [comment]
Closed by merge?

**Comment by slhck** [comment]
Yes! Should have used "fixes" in the title. Thanks for the reminder!
