### ISSUE TITLE
Hard-coded `/home/dockeruser` in template

### ISSUE THREAD

**Issue by rbq** [konstruktoid/ansible-docker-rootless#5]
https://github.com/konstruktoid/ansible-docker-rootless/blob/7f6367ebd1949c61368aab06e4649461ab435991/templates/docker_rootless.service.j2#L11-L13

**Comment by konstruktoid** [comment]
Hi @rbq, and thanks for the report.
Commited https://github.com/konstruktoid/ansible-docker-rootless/commit/7fe1750496ff0e063136e2aee23d7801a81e6f98
